/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#000a24",
        "on-primary": "#ffffff",
        "primary-container": "#14213d",
        "on-primary-container": "#ffffff",
        "inverse-primary": "#b9c6ea",
        "primary-fixed": "#d9e2ff",
        "primary-fixed-dim": "#b9c6ea",
        "on-primary-fixed": "#0d1b36",
        "on-primary-fixed-variant": "#3a4664",
        "primary-tint": "#d9e2ff",

        "secondary": "#855300",
        "on-secondary": "#ffffff",
        "secondary-container": "#ffa515",
        "on-secondary-container": "#684000",
        "secondary-fixed": "#ffddb8",
        "secondary-fixed-dim": "#ffb95f",
        "on-secondary-fixed": "#2a1700",
        "on-secondary-fixed-variant": "#653e00",
        "secondary-tint": "#ffddb8",

        "tertiary": "#130900",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#321d00",
        "on-tertiary-container": "#a58359",
        "tertiary-fixed": "#ffddb6",
        "tertiary-fixed-dim": "#e7c092",
        "on-tertiary-fixed": "#2a1800",
        "on-tertiary-fixed-variant": "#5c421e",

        "surface": "#fbf8fb",
        "surface-dim": "#dbd9dc",
        "surface-bright": "#fbf8fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f6",
        "surface-container": "#f0edf0",
        "surface-container-high": "#eae7ea",
        "surface-container-highest": "#e4e2e5",
        "surface-variant": "#e4e2e5",
        "on-surface": "#1b1b1e",
        "on-surface-variant": "#45464d",
        "inverse-surface": "#303033",
        "inverse-on-surface": "#f2f0f3",
        "surface-tint": "#525e7d",

        "background": "#fbf8fb",
        "on-background": "#1b1b1e",
        "outline": "#75777e",
        "outline-variant": "#c5c6ce",
        "border-subtle": "#c5c6ce",
        "text-muted": "#75777e",

        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "error-tint": "#ffdad6",
        "warning-tint": "#ffddb8",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "sm": "0.125rem",
        "md": "0.25rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "base": "8px",
        "gutter": "24px",
        "margin": "32px",
        "container-max": "1440px",
        "space-1": "4px",
        "space-2": "8px",
        "space-3": "12px",
        "space-4": "16px",
        "space-6": "24px",
        "space-8": "32px",
        "space-12": "48px",
      },
      fontFamily: {
        "headline-lg": ["League Spartan", "sans-serif"],
        "headline-md": ["League Spartan", "sans-serif"],
        "headline-sm": ["League Spartan", "sans-serif"],
        "label-md": ["League Spartan", "sans-serif"],
        "button": ["League Spartan", "sans-serif"],
        "nav-link": ["League Spartan", "sans-serif"],
        "body-lg": ["Libre Baskerville", "serif"],
        "body-md": ["Libre Baskerville", "serif"],
        "body": ["Libre Baskerville", "serif"],
        "display": ["League Spartan", "sans-serif"],
        "caption": ["Libre Baskerville", "serif"],
        "body-emphasis": ["Libre Baskerville", "serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "button": ["16px", { lineHeight: "1", fontWeight: "700" }],
        "nav-link": ["15px", { lineHeight: "1", fontWeight: "500" }],
        "display": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "caption": ["14px", { lineHeight: "1.4", fontWeight: "400" }],
      }
    },
  },
  plugins: [],
}
